version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/login"
    depends_on:
      - mongo
    volumes:
      - .:/app  # Mount the current directory to /app in the container

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: